<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Whiteboard</AssemblyName>
    <RootNamespace>Whiteboard</RootNamespace>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>2.1.0</Version>

    <!-- Иконка EXE-файла и панели задач -->
    <ApplicationIcon>whiteboard.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- Та же иконка как ресурс — чтобы задать её окнам через Icon="..." -->
    <Resource Include="whiteboard.ico" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
